name: 'build test'

on: [pull_request, push]

jobs:
  verify:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout...
        uses: actions/checkout@v4

      - name: Set up JDK...
        uses: actions/setup-java@v4
        with:
          # While BQ 3 works with Java 11, Hazelcast 5.x requires Java 17
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test Caffeine...
        run: cd jcache-caffeine-example && mvn -ntp clean verify

      - name: Build and test Ehcache...
        run: cd jcache-ehcache-example && mvn -ntp clean verify

      - name: Build and test Hazelcast...
        run: cd jcache-hazelcast-example && mvn -ntp clean verify